services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"