apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service_http1.port }}
      targetPort: {{ .Values.service_http1.port_name }}
      protocol: {{ .Values.service_http1.protocol }}
      name: {{ .Values.service_http1.port_name }}
    - port: {{ .Values.service_http2.port }}
      targetPort: {{ .Values.service_http2.port_name }}
      protocol: {{ .Values.service_http2.protocol }}
      name: {{ .Values.service_http2.port_name }}
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}